apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: workload02-
bases:
- ../../base/
patchesJson6902:
- target:
    group: run.tanzu.vmware.com
    version: v1alpha3
    kind: ClusterBootstrap
    name: base
  path: clusterbootstrap-patch.yaml
- target:
    group: cluster.x-k8s.io
    version: v1beta1
    kind: Cluster
    name: base
  path: cluster-patch.yaml
