---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  annotations:
    osInfo: photon,3,amd64
    tkg.tanzu.vmware.com/cluster-controlplane-endpoint: workload01-vip.tta.lab
    tkg/plan: dev
  labels:
    tkg.tanzu.vmware.com/cluster-name: workload01
  name: workload01
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 100.96.0.0/11
    services:
      cidrBlocks:
      - 100.64.0.0/13
  topology:
    class: tkg-vsphere-default-v1.0.0
    controlPlane:
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: image-type=ova,os-name=photon
      replicas: 1
    variables:
    - name: cni
      value: antrea
    - name: controlPlaneCertificateRotation
      value:
        activate: true
        daysBefore: 90
    - name: auditLogging
      value:
        enabled: false
    - name: podSecurityStandard
      value:
        audit: baseline
        deactivated: false
        warn: baseline
    - name: apiServerEndpoint
      value: workload01-vip.tta.lab
    - name: aviAPIServerHAProvider
      value: false
    - name: vcenter
      value:
        cloneMode: fullClone
        datacenter: /Datacenter
        datastore: /Datacenter/datastore/iscsi01
        folder: /Datacenter/vm/tkg-vm
        network: /Datacenter/network/dvs_service-vlan31-pg
        resourcePool: /Datacenter/host/Compute/Resources/tkg-pool
        server: vcsa.tta.lab
        storagePolicyID: ""
        template: /Datacenter/vm/tkg-template/photon-3-kube-v1.25.7+vmware.2
        tlsThumbprint: ""
    - name: user
      value:
        sshAuthorizedKeys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDYR6BYL8HmCS94CUFAVa6Zy49N3jsb5rI2YE9tp2SvMhZHSMfAJZ8aQAItyW/JrYr7C4GRC3c5C8j9AJopxT9Hqs7eYk21sMHDCOUuklxQlpAS2GO7Al4krgqFsFV+EyHqlcyYnUbqybxBGBDgFoA+6DC+mJl6Wcymru7H1QKAPjHww+KYILWi5nfsb+ae+eBK0IiwLxgdWLjR8I3IYmQJBK5XGYJBUALJTHvmC57gU5ac9bEONYf8kRdI4AdYGbFqEtTt+Ot7F4KkFRrdMIy2DhvCKw35meoBIW8sDO4idLNpn33AA1T5oNFy7l2pNfWSePdwtEavVSRH6qi+VZwxWDrnpAiHlnyX1LGecLIR61P8zE7Fe/mpbNcooZ+5TSn1TsfgZEHoC3oarO3N+SOftUVc4OaQnYAtBc5jBaN8Aoiy6nlhg5b8vB1F2m+DGmaWr8CqGUM4KbZljrUkDQXXfpxbLthroAVvdivFr5EpjkZ7D7jXZFdTymTuCyh1mv3QE4mtfOKCBDQ+p1S5IvWiKn2UMo/w2Om5jGsICq4TWpjRTqSLhcmlP7KuujCnBnD4FghVDAUfBw1x1DyV3w6bGgZOhIq4bEoRSof2VDBZGMZqTGxg9omDFjOquryuoG8nVpZcxfRc2m4Fo8EXV3YrTWKbs/rQI5O4He3QQUuCZw==
    - name: controlPlane
      value:
        machine:
          diskGiB: 20
          memoryMiB: 4096
          numCPUs: 2
    - name: worker
      value:
        count: 1
        machine:
          diskGiB: 20
          memoryMiB: 4096
          numCPUs: 2
    version: v1.25.7+vmware.2-tkg.1
    workers:
      machineDeployments:
      - class: tkg-worker
        metadata:
          annotations:
            run.tanzu.vmware.com/resolve-os-image: image-type=ova,os-name=photon
        name: md-0
        replicas: 1
