---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tkg
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/ttani03/tunacon9-kaas-home
